question_data = [
    {"text": "The Bible was first written in the English language?.", "answer": "False"},
    {"text": "Genesis is the first book in the Bible", "answer": "True"},
    {"text": "Matthew, Mark, Luke, John are the four Gospel books telling about Jesus's life on Earth? .",
     "answer": "True"},
    {"text": "Jesus directly wrote the book of Revelation", "answer": "False"},
    {"text": "There are 37 books in the Old Testament", "answer": "False"},
    {"text": "David wrote the entire book of Psalms.", "answer": "False"},
    {"text": "Jude is the last book in the Bible", "answer": "False"},
    {"text": "There are 39 books in the Old Testament", "answer": "True"},
    {"text": "There are 27 books in the New Testament", "answer": "True"},
    {"text": "Psalms is the longest book in the Bible", "answer": "True"},
    {"text": "Revelation is the last book in the Bible", "answer": "True"},
    {"text": "The Bible has 66 books", "answer": "False"},
    {"text": "3 John is the shortest book in the Bible", "answer": "True"},
    {"text": "The Bible was first written in the English language", "answer": "False"},
    {"text": "Paul  wrote the most words in the Bible", "answer": "False"},
    {"text": "Most of the Old Testament was given in the Hebrew language", "answer": "True"},
    {"text": "Which NT book has Jesus' Sermon on the Mount? - Matthew", "answer": "True"},
    {"text": "3 John is the shortest book in the Bible", "answer": "True"},
    {"text": "Most of the New Testament was given in the Greek language", "answer": "True"},
    {"text": "Paul  wrote 13 books of the bible", "answer": "True"},
    {"text": "Moses  wrote the most words in the Bible", "answer": "False"},
    {"text": "Mark was most likely the first Gospel written.", "answer": "True"},
    {"text": "John was most likely the last Gospel written.", "answer": "True"},
    {"text": "1 Thessalonians was most likely the first of Paul's letters written.", "answer": "True"},
    {"text": "Revelation was most likely the last New Testament book written.", "answer": "True"},
    {"text": "God took 6 days to create the world.", "answer": "True"},
    {"text": "God created man on the 6th day.", "answer": "True"},
    {"text": "Adam was the first man.", "answer": "True"},
    {"text": "Eve was the first woman.", "answer": "True"},
    {"text": "Adam and Eve lived in the Garden of Eden at the beginning of the world.", "answer": "True"},
    {"text": "Cain, Abel, and Seth were the three sons of Adam and Eve listed in the Bible.", "answer": "True"},
    {"text": "Noah was the one God told to build an ark.", "answer": "True"},
    {"text": "Noah’s three sons were Shem, Ham, and Japheth.", "answer": "True"},
    {"text": "It rained for 40 days and 40 nights when Noah was on the ark.", "answer": "True"},
    {"text": "Eight people were saved on the ark.", "answer": "True"},
    {"text": "God’s sign to Noah that He would never destroy the earth again was a rainbow.", "answer": "True"},
    {"text": "Men were trying to build a tower to Heaven at the Tower of Babel.", "answer": "True"},
    {"text": "God confused their languages to make them spread out across the earth.", "answer": "True"},
    {"text": "God called Abram out of Ur to move to Canaan.", "answer": "True"},
    {"text": "Abram’s wife was Sarai.", "answer": "True"},
    {"text": "God promised Abram and Sarah a son even though they were too old.", "answer": "True"},
    {"text": "God promised Abram he would have more descendants than the stars.", "answer": "True"},
    {"text": "Hagar was Abram’s handmaid.", "answer": "True"},
    {"text": "It was Sarah’s idea for Abram to have a child with Hagar.", "answer": "True"},
    {"text": "Ishmael was Abram’s first son.", "answer": "True"},
    {"text": "Abram’s name was changed to Abraham.", "answer": "True"},
    {"text": "Sarai’s name was changed to Sarah.", "answer": "True"},
    {"text": "Isaac was Abraham’s second son.", "answer": "True"},
    {"text": "Sarah was the mother of Isaac.", "answer": "True"},
    {"text": "Hagar and her son left into the desert.", "answer": "True"},
    {"text": "Abraham sent his oldest servant to find Isaac a wife.", "answer": "True"},
    {"text": "The servant chose Rebekah as Isaac’s wife.", "answer": "True"},
    {"text": "Isaac’s sons were Jacob and Esau.", "answer": "True"},
    {"text": "Esau was born first, with Jacob grabbing his heel.", "answer": "True"},
    {"text": "Esau hunted to provide food for the family.", "answer": "True"},
    {"text": "Isaac favored Esau over Jacob.", "answer": "True"},
    {"text": "Jacob stayed at home with his mother most of the time.", "answer": "True"},
    {"text": "Esau exchanged his birthright for some stew.", "answer": "True"},
    {"text": "Rebekah suggested that Jacob should steal the blessing from Esau.", "answer": "True"},
    {"text": "Esau threatened to kill Jacob after losing his blessing.", "answer": "True"},
    {"text": "Jacob wanted to marry Rachel when he met Laban.", "answer": "True"},
    {"text": "Laban tricked Jacob into marrying Leah first.", "answer": "True"},
    {"text": "Jacob had to work another seven years to marry Rachel.", "answer": "True"},
    {"text": "Joseph was the first son Jacob had with Rachel.", "answer": "True"},
    {"text": "God changed Jacob’s name to Israel before his meeting with Esau.", "answer": "True"},
    {"text": "Joseph had 11 brothers.", "answer": "True"},
    {"text": "Jacob gave Joseph a coat of many colors, which made his brothers jealous.", "answer": "True"},
    {"text": "Joseph’s dreams said he would rule over his brothers.", "answer": "True"},
    {"text": "Joseph’s brothers sold him to slave traders.", "answer": "True"},
    {"text": "Joseph’s brothers told their father he was killed by a wild animal.", "answer": "True"},
    {"text": "The slave traders took Joseph to Egypt.", "answer": "True"},
    {"text": "Potiphar, captain of Pharaoh’s guards, bought Joseph.", "answer": "True"},
    {"text": "Potiphar’s wife got Joseph thrown into prison by lying about him.", "answer": "True"},
    {"text": "Joseph was alone in prison with no one else.", "answer": "False"},
    {"text": "Joseph interpreted the dreams of the Pharaoh’s cupbearer and chief baker.", "answer": "True"},
    {"text": "Joseph was summoned out of prison to entertain Pharaoh.", "answer": "False"},
    {"text": "Joseph was made second in command of Egypt by Pharaoh.", "answer": "True"},
    {"text": "Joseph predicted a seven-year famine by interpreting Pharaoh’s dream.", "answer": "True"},
    {"text": "Joseph’s brothers came to Egypt because of the famine.", "answer": "True"},
    {"text": "Benjamin was Jacob’s second son with Rachel.", "answer": "True"},
    {"text": "Joseph told his brothers to leave Benjamin in Egypt and not return.", "answer": "False"},
    {"text": "Judah volunteered to stay in Egypt instead of Benjamin.", "answer": "True"},
    {"text": "Joseph told his brothers to bring their families and father to Egypt.", "answer": "True"},
    {"text": "Moses’ mother saved him from Egyptian soldiers by hiding him in a basket in the river.", "answer": "True"},
    {"text": "After killing an Egyptian, Moses celebrated in Egypt.", "answer": "False"},
    {"text": "God spoke to Moses through a burning bush in the desert.", "answer": "True"},
    {"text": "When Moses threw his staff on the ground, it turned into a snake.", "answer": "True"},
    {"text": "Moses told Pharaoh that God wanted the Israelite slaves freed.", "answer": "True"},
    {"text": "God sent 10 plagues on Egypt.", "answer": "True"},
    {"text": "The final plague was frogs covering the land.", "answer": "False"},
    {"text": "Pharaoh’s army caught the Israelites before the Red Sea.", "answer": "False"},
    {"text": "God parted the Red Sea to save the Israelites.", "answer": "True"},
    {"text": "The Egyptian army survived after chasing the Israelites into the Red Sea.", "answer": "False"},
    {"text": "God fed the Israelites with manna and quail in the desert.", "answer": "True"},
    {"text": "God gave Moses the Ten Commandments on Mt. Sinai.", "answer": "True"},
    {"text": "The Israelites made a golden calf at Mt. Sinai.", "answer": "True"},
    {"text": "The spies were scared of giants in Canaan.", "answer": "True"},
    {"text": "Joshua and Caleb were the only two Israelites allowed into the Promised Land.", "answer": "True"},
    {"text": "God made the walls of Jericho fall so Joshua could conquer the city.", "answer": "True"},
    {"text": "After Joshua died, kings ruled Israel immediately.", "answer": "False"},
    {"text": "Deborah was a woman judge who led Israel to victory.", "answer": "True"},
    {"text": "Gideon defeated the Midianites with thousands of soldiers.", "answer": "False"},
    {"text": "Samson took a Nazarite vow from birth and fought the Philistines.", "answer": "True"},
    {"text": "Samson killed 1,000 Philistines with a donkey’s jawbone.", "answer": "True"},
    {"text": "Delilah asked Samson where his power came from.", "answer": "True"},
    {"text": "Samson died peacefully in old age.", "answer": "False"},
    {"text": "Saul was the first king of Israel.", "answer": "True"},
    {"text": "Samuel anointed Saul as king.", "answer": "True"},
    {"text": "The Philistines took the Ark of the Covenant.", "answer": "True"},
    {"text": "The idol beside the Ark in the Philistine temple stood tall and unharmed.", "answer": "False"},
    {"text": "Saul made a sacrifice to God that only priests should make.", "answer": "True"},
    {"text": "Saul obeyed God completely when conquering the Amalekites.", "answer": "False"},
    {"text": "Saul kept King Agag alive against God’s command.", "answer": "True"},
    {"text": "God took the kingdom from Saul for disobedience.", "answer": "True"},
    {"text": "Samuel anointed David as king after Saul.", "answer": "True"},
    {"text": "David was a shepherd for his father.", "answer": "True"},
    {"text": "Goliath mocked God and challenged the Israelites.", "answer": "True"},
    {"text": "Saul gave David his own armor to fight Goliath.", "answer": "True"},
    {"text": "David took five stones from the brook to fight Goliath.", "answer": "True"},
    {"text": "David needed three sling-throws to defeat Goliath.", "answer": "False"},
    {"text": "Jonathan, Saul’s son, became David’s enemy.", "answer": "False"},
    {"text": "Saul threw a javelin to try to kill David.", "answer": "True"},
    {"text": "Jonathan warned David about Saul’s plans to kill him.", "answer": "True"},
    {"text": "David ran to the land of the Philistines to escape Saul.", "answer": "True"},
    {"text": "Saul gave up chasing David quickly.", "answer": "False"},
    {"text": "David spared Saul’s life once.", "answer": "False"},
    {"text": "David spared Saul’s life in a cave the first time.", "answer": "True"},
    {"text": "David spared Saul’s life in his camp the second time.", "answer": "True"},
    {"text": "Samuel was the last judge of Israel who died after Saul’s peace with David.", "answer": "True"},
    {"text": "David went to Philistia after Saul continued hunting him.", "answer": "True"},
    {"text": "When Saul couldn’t hear from God, he sought advice from a witch.", "answer": "True"},
    {"text": "Saul asked to speak to the prophet Elijah.", "answer": "False"},
  {"text": "Saul died by falling on his own sword.", "answer": "True"},
  {"text": "Only one of Saul’s sons died in the same battle.", "answer": "False"},
  {"text": "All of Israel immediately considered David their king.", "answer": "False"},
  {"text": "Joab was David’s captain of the army.", "answer": "True"},
  {"text": "David committed adultery with Bathsheba while staying in Jerusalem.", "answer": "True"},
  {"text": "Uriah was Bathsheba’s husband.", "answer": "True"},
  {"text": "David had Uriah promoted after Bathsheba became pregnant.", "answer": "False"},
  {"text": "Nathan was the prophet who rebuked David.", "answer": "True"},
  {"text": "Bathsheba’s first child with David lived a long life.", "answer": "False"},
  {"text": "Solomon was the second child born to David and Bathsheba.", "answer": "True"},
  {"text": "Absalom, David’s son, started a rebellion against him.", "answer": "True"},
  {"text": "David abandoned Jerusalem when Absalom approached.", "answer": "True"},
  {"text": "Absalom’s hair got caught in a tree during battle.", "answer": "True"},
  {"text": "Joab killed Absalom.", "answer": "True"},
  {"text": "Joab remained captain even after killing Absalom.", "answer": "False"},
  {"text": "David’s second sin recorded in the Bible was taking a census.", "answer": "True"},
  {"text": "The Philistines were David’s main enemy during his reign.", "answer": "True"},
  {"text": "David’s reign as king is recorded in the books of 1st and 2nd Samuel.", "answer": "True"},
  {"text": "David wrote most of the book of Psalms.", "answer": "True"},
  {"text": "Solomon, David’s son, became king after him.", "answer": "True"},
  {"text": "Solomon prayed to God for great wealth.", "answer": "False"},
  {"text": "Solomon built a temple for the Lord.", "answer": "True"},
  {"text": "The Queen of Sheba visited Solomon.", "answer": "True"},
  {"text": "Solomon had 700 wives.", "answer": "True"},
  {"text": "Solomon always followed the Lord.", "answer": "False"},
  {"text": "Solomon’s wives turned him away from God.", "answer": "True"},
  {"text": "The kingdom remained united after Solomon’s rule.", "answer": "False"},
  {"text": "1st and 2nd Kings and 1st and 2nd Chronicles record the history of all the kings.", "answer": "True"},
  {"text": "Solomon wrote Song of Solomon, Proverbs, and some Psalms.", "answer": "True"},
  {"text": "There were 20 kings of Judah.", "answer": "True"},
  {"text": "There were 19 kings of Israel.", "answer": "True"},
  {"text": "The Babylonians conquered Judah and took Daniel to their country.", "answer": "True"},
  {"text": "Daniel interpreted the dream of King Nebuchadnezzar.", "answer": "True"},
  {"text": "Darius was the last king Daniel served under in the Bible.", "answer": "True"},
  {"text": "Daniel was thrown into a lion’s den for praying to God.", "answer": "True"},
  {"text": "Daniel’s three friends were named Shadrach, Meshach, and Abednego.", "answer": "True"},
  {"text": "Shadrach, Meshach, and Abednego were thrown into a fiery furnace for worshiping an idol.", "answer": "False"},
  {"text": "Nehemiah returned to Israel to rebuild Jerusalem’s walls.", "answer": "True"},
  {"text": "Esther was an Israelite who became queen and saved her people.", "answer": "True"},
  {"text": "Esther waited to be summoned before talking to the king.", "answer": "False"},
  {"text": "Cyrus allowed the Israelites to return to their homeland.", "answer": "True"},
  {"text": "Jesus came from the lineage of David.", "answer": "True"},
  {"text": "Mary was Jesus’ human mother.", "answer": "True"},
  {"text": "Joseph was Jesus’ adoptive father.", "answer": "True"},
  {"text": "Jesus’ birth father was Joseph.", "answer": "False"},
  {"text": "Jesus was born in Bethlehem.", "answer": "True"},
  {"text": "Jesus’ family went to Egypt to escape King Herod.", "answer": "True"},
  {"text": "Jesus never obeyed his parents because he was God.", "answer": "False"},
  {"text": "Jesus was an only child.", "answer": "False"},
  {"text": "The Bible names four of Jesus’ brothers.", "answer": "True"},
  {"text": "None of Jesus’ sisters are named in the Bible.", "answer": "True"},
  {"text": "John the Baptist was Jesus’ most famous cousin.", "answer": "True"},
  {"text": "John the Baptist wore clothes made of goat hair.", "answer": "False"},
  {"text": "John the Baptist baptized Jesus.", "answer": "True"},
  {"text": "God spoke from heaven when Jesus was baptized.", "answer": "True"},
  {"text": "Jesus was tempted by Satan in the wilderness.", "answer": "True"},
  {"text": "Before preaching, Jesus was a carpenter.", "answer": "True"},
  {"text": "Jesus’ hometown was Nazareth.", "answer": "True"},
  {"text": "Jesus turned water into Coca-Cola.", "answer": "False"},
  {"text": "Jesus healed the sick and cast out demons while traveling.", "answer": "True"},
  {"text": "Jesus avoided people with bad reputations.", "answer": "False"},
  {"text": "Jesus walked on water at the Sea of Galilee.", "answer": "True"},
  {"text": "At first, Jesus’ family tried to stop his ministry.", "answer": "True"},
  {"text": "Jesus said anyone who obeys God is his true family.", "answer": "True"},
  {"text": "Everyone loved and accepted Jesus wherever he went.", "answer": "False"},
  {"text": "Nicodemus came at night to ask Jesus questions.", "answer": "True"},
  {"text": "Jesus welcomed all people to follow him.", "answer": "True"},
  {"text": "Jesus chose 12 disciples.", "answer": "True"},
  {"text": "Matthew was a fisherman before following Jesus.", "answer": "False"},
  {"text": "Jesus used spit as part of healing miracles.", "answer": "True"},
  {"text": "‘Jesus wept’ is the shortest verse in the Bible.", "answer": "True"},
  {"text": "Jesus wept because Lazarus was raised from the dead.", "answer": "False"},
  {"text": "Lazarus had been dead four days when Jesus arrived.", "answer": "True"},
  {"text": "Jesus prayed and spoke to raise Lazarus from the dead.", "answer": "True"},
  {"text": "Several women paid for Jesus’ ministry.", "answer": "True"},
  {"text": "Jesus cast out a demon named Legion in the region of the Gerasenes.", "answer": "True"},
  {"text": "Jesus had the power to raise the dead.", "answer": "True"},
  {"text": "Jesus fed 5,000 people with five loaves and two fish.", "answer": "True"},
  {"text": "Jesus said handwashing is never important.", "answer": "False"},
  {"text": "Peter and Andrew were fishing when Jesus called them.", "answer": "True"},
  {"text": "Elijah and Moses appeared when Jesus was transfigured.", "answer": "True"},
  {"text": "Jesus told children to stay away while he taught adults.", "answer": "False"},
  {"text": "Bartimaeus was blind until Jesus healed him.", "answer": "True"},
  {"text": "Jesus stayed quiet in the temple when he saw corruption.", "answer": "False"},
  {"text": "Jesus fed 5,000 people with bread and fish.", "answer": "True"},
  {"text": "Jesus healed 10 lepers, but only one returned.", "answer": "True"},
  {"text": "At the Last Supper, Jesus washed the disciples’ feet.", "answer": "True"},
  {"text": "Jesus said only large offerings matter to God.", "answer": "False"},
  {"text": "A woman poured perfume on Jesus’ feet at Simon’s house.", "answer": "True"},
  {"text": "Judas Iscariot betrayed Jesus.", "answer": "True"},
  {"text": "Jesus prayed in the Garden of Gethsemane after the Last Supper.", "answer": "True"},
  {"text": "The Jewish leaders tried to set Jesus free.", "answer": "False"},
  {"text": "Roman soldiers gave Jesus a crown of thorns.", "answer": "True"},
  {"text": "Pilate was the Roman governor over Jesus’ trial.", "answer": "True"},
  {"text": "Pilate washed his hands to show he was innocent.", "answer": "True"},
  {"text": "Peter cut off a soldier’s ear when Jesus was arrested.", "answer": "True"},
  {"text": "Jesus didn’t know he would be arrested and killed.", "answer": "False"},
  {"text": "Peter denied Jesus three times.", "answer": "True"},
  {"text": "The temple curtain tore when Jesus died.", "answer": "True"},
  {"text": "Jesus rose from the dead after being buried.", "answer": "True"},
  {"text": "A small rock was rolled away from Jesus’ tomb.", "answer": "False"},
  {"text": "Jesus rose on Sunday, the first day of the week.", "answer": "True"},
  {"text": "Jesus stayed on earth 40 days after rising.", "answer": "True"},
  {"text": "Jesus went to Heaven by climbing a mountain.", "answer": "False"},
  {"text": "Over 500 people saw Jesus after he rose from the dead.", "answer": "True"},
  {"text": "Peter’s vision about unclean animals meant that all people, including non-Jews, "
           "can be made clean through Jesus.", "answer": "True"},
  {"text": "Jesus’ followers were first called Christians in Antioch.", "answer": "True"},
  {"text": "Peter was rescued from prison by an angel.", "answer": "True"},
  {"text": "Barnabas went with Paul on his early mission trips.", "answer": "True"},
  {"text": "Paul had a vision of a man calling him to come over to Carthage.", "answer": "False"},
  {"text": "God sent an earthquake to rescue Paul and Silas from prison in Philippi, but they "
           "stayed to share the Gospel.", "answer": "True"},
  {"text": "The Philippian jailer asked Paul, 'What must I do to be saved?'", "answer": "True"},
  {"text": "Paul and Silas told the Philippian jailer to believe in the Lord Jesus to be saved.", "answer": "True"},
  {"text": "Paul’s goal in his missionary journeys was to take the Gospel everywhere and finally preach in Rome.", "answer": "True"},
  {"text": "The 10 Commandments are found in Exodus 20 and Deuteronomy 5.", "answer": "True"},
  {"text": "Moses received the 10 Commandments from God.", "answer": "True"},
  {"text": "The introduction to the Commandments is: 'I am the LORD your God who brought you out of Egypt.'", "answer": "True"},
  {"text": "The 1st commandment is: You shall have no other gods before me.", "answer": "True"},
  {"text": "The 2nd commandment is: You shall not make idols.", "answer": "True"},
  {"text": "The 3rd commandment is: You shall not misuse the name of the LORD your God.", "answer": "True"},
  {"text": "The 4th commandment is: Observe the Sabbath day by keeping it holy.", "answer": "True"},
  {"text": "The 5th commandment is: Honor your father and mother.", "answer": "True"},
  {"text": "The 6th commandment is: You shall not murder.", "answer": "True"},
  {"text": "The 7th commandment is: You shall not commit adultery.", "answer": "True"},
  {"text": "The 8th commandment is: You shall not steal.", "answer": "True"},
  {"text": "The 9th commandment is: You shall not give false testimony.", "answer": "True"},
  {"text": "The 10th commandment is: You shall not covet.", "answer": "True"},
  {"text": "Jesus said the Old Testament rules don’t matter anymore.", "answer": "False"},
  {"text": "Jesus summarized all the Old Testament rules into two commandments.", "answer": "True"},
  {"text": "The first and greatest commandment is to love God with all your heart, soul, mind, and strength.", "answer": "True"},
  {"text": "The second greatest commandment is to love your neighbor as yourself.", "answer": "True"},
  {"text": "The Fruit of the Spirit is found in Galatians 5.", "answer": "True"},
  {"text": "Paul is the human author who wrote the book of Galatians.", "answer": "True"},
  {"text": "Bananas are a fruit of the Spirit.", "answer": "False"},
  {"text": "The Fruit of the Spirit includes love, joy, peace, patience, kindness, goodness, faithfulness, "
           "gentleness, and self-control.", "answer": "True"},
  {"text": "The opposite of the Fruit of the Spirit are called 'the works of the flesh.'", "answer": "True"},
  {"text": "The Lord’s Prayer is found in Matthew 6.", "answer": "True"},
  {"text": "Jesus taught the Lord’s Prayer.", "answer": "True"},
  {"text": "There are seven petitions in the Lord’s Prayer.", "answer": "True"},
  {"text": "The first petition in the Lord’s Prayer is 'Hallowed be your name.'", "answer": "True"},
  {"text": "The second petition in the Lord’s Prayer is 'Your kingdom come.'", "answer": "True"},
  {"text": "The third petition in the Lord’s Prayer is 'Your will be done on Earth.'", "answer": "True"},
  {"text": "The fourth petition in the Lord’s Prayer is 'Give us our daily bread.'", "answer": "True"},
  {"text": "The fifth petition in the Lord’s Prayer is 'Forgive our debts.'", "answer": "True"},
  {"text": "The sixth petition in the Lord’s Prayer is 'Don’t lead us into temptation.'", "answer": "True"},
  {"text": "The seventh petition in the Lord’s Prayer is 'Deliver us from evil.'", "answer": "True"},
  {"text": "The more words we say in prayer, the better they are.", "answer": "False"}



]









# question_data = [
#     {"type": "boolean",
#      "difficulty": "easy",
#      "category": "Entertainment: Music",
#      "question": ": The Bible was first written in the English language?.",
#      "correct_answer": "False",
#      "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Geography",
#      "question": "Antarctica is the largest desert in the world.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
#      "question": "A Saxophone is a brass instrument.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Sports",
#      "question": "The Olympics tennis court is a giant green screen.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
#      "question": "Arcade Fire&#039;s &#039;The Suburbs&#039; won the Album of the Year award in the 2011 Grammys.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
#      "question": "The names of Roxas&#039;s Keyblades in Kingdom Hearts are &quot;Oathkeeper&quot; and &quot;Oblivion&quot;.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium",
#      "category": "Entertainment: Cartoon &amp; Animations",
#      "question": "Blue Danube was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
#      "question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series&#039; history.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Geography",
#      "question": "California is larger than Japan.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
#      "question": "McCree from Overwatch originally started as a character that was going to appear in a scrapped Starcraft game.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
#      "question": "In the Monster Hunter Series, G-Rank is the highest possible prestige a Hunter can recieve.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium",
#      "category": "Entertainment: Video Games",
#      "question": "Hidden in the files for &quot;Mario Kart Arcade GP&quot; is a picture of the Beslan school hostage crisis.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
#      "question": "An average human can go two weeks without water.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#      "question": "Ping-Pong originated in England", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#      "question": "The Sun rises from the North.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "hard", "category": "Vehicles",
#      "question": "The term &quot;GTO&quot; was originated by Ferrari?",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
#      "question": "An atom contains a nucleus.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#      "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Comics",
#      "question": "The X-Men&#039;s Storm and Nightcrawler were originally planned to be characters in DC Comics&#039; Legion of Super-Heroes.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
#      "question": "Metallica collaborated with Rowan Atkinson&#039;s Mr Bean on a 1992 comic relief single.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
#      "question": "The band &quot;Panic! At the Disco&quot; has released 4 albums total",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy",
#      "category": "Entertainment: Japanese Anime &amp; Manga",
#      "question": "In the &quot;Toaru Kagaku no Railgun&quot; anime,  espers can only reach a maximum of level 6 in their abilities.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Geography",
#      "question": "You could walk from Norway to North Korea while only passing through Russia.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Geography",
#      "question": "Is Tartu the capital of Estonia?", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
#      "question": "In Pok&eacute;mon, Arbok evolves into Seviper.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
#      "question": "In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium",
#      "category": "Entertainment: Video Games",
#      "question": "Minecraft wasn&rsquo;t the original name to Minecraft.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science: Gadgets",
#      "question": "The communication protocol NFC stands for Near-Field Control.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Science: Mathematics",
#      "question": "E = MC3", "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
#      "question": "In &quot;Sonic Adventure&quot;, you are able to transform into Super Sonic at will after completing the main story.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Mythology",
#      "question": "In Greek mythology, Hera is the goddess of harvest.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "History",
#      "question": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
#      "question": "Daft Punk originated in France.", "correct_answer": "True",
#      "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium",
#                                        "category": "Entertainment: Video Games",
#                                        "question": "In the game &quot;Until Dawn&quot; Emily is the only playable character who can be killed by another playable character directly.",
#                                        "correct_answer": "True",
#                                        "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Animals",
#      "question": "The Platypus is a mammal.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Politics",
#      "question": "Jeb Bush was elected as Governor of Florida in 2002, starting his political career.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
#      "question": "Centripetal force is an apparent force that acts outward on a body moving around a center, arising from the body&#039;s inertia.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium",
#      "category": "Entertainment: Video Games",
#      "question": "In World of Warcraft lore, Thrall is the original wielder of &quot;Doomhammer&quot;.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
#      "question": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
#      "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
#      "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy",
#      "category": "Entertainment: Japanese Anime &amp; Manga",
#      "question": "Clefairy was intended to be Ash&#039;s starting Pok&eacute;mon in the pilot episode of the cartoon.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
#      "question": "The Kerbol System (from Kerbal Space Program) includes a Saturn analogue.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Politics",
#      "question": "Denmark has a monarch.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
#      "question": "Ada Lovelace is often considered the first computer programmer.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
#      "question": "The vapor produced by e-cigarettes is actually water.",
#      "correct_answer": "False", "incorrect_answers": ["True"]},
#     {"type": "boolean", "difficulty": "easy", "category": "Sports",
#      "question": "There are a total of 20 races in Formula One 2016 season.",
#      "correct_answer": "False", "incorrect_answers": ["True"]}
# ]
